### ISSUE TITLE
Wrong name of Easy Challenge #266 folder.

### ISSUE THREAD

**Issue by Ouss4** [FreddieV4/DailyProgrammerChallenges#152]
This week's easy challenge has a `:` in the name of the folder, which causes some problems as we can't have `:` in a folder name.

The sequence `\/:?*"<>` should be ignored in folders name.

**Comment by freddiev4** [comment]
Hmm... Thought I had this issue fixed a long time ago. I'll try to hash it
out for good by tonight.

**Comment by Ouss4** [comment]
Actually you did. But only for the `get_all_submissions` function, not for `get_current_week` function.

This regex is missing : `t = re.sub(r'[<>:\"\\\/|?*]', '', title)` in the week function.
