### ISSUE TITLE
Reserved characters in directory names causing errors - Windows

### ISSUE THREAD

**Issue by JamesJDillon** [FreddieV4/DailyProgrammerChallenges#17]
When trying to clone the project (using: git clone https://github.com/FreddieV4/DailyProgrammerChallenges.git), I'm running in to errors that I think are due using a reserved character in a directory name. When I try and clone I get:

```
    fatal: cannot create directory at 'Easy Challenges/Challenge #0257 [Easy] In what year were most presidents alive?': Invalid argument
```

I've googled around, and found that windows has a bunch of reserved characters that cannot be used in directory names such as:
- < (less than)
- > (greater than)
- : (colon)
- " (double quote)
- / (forward slash)
- \ (backslash)
- | (vertical bar or pipe)
- ? (question mark)
- \* (asterisk)

The question mark in "Challenge #0257 [Easy] In what year were most presidents alive?" needs to be removed, and I'd gladly do it myself but I can't clone the project to fix it.

**Comment by freddiev4** [comment]
@JamesJDillon I'm aware of this issue. I thought I had caught all of the directories using reserved chars but I guess not :). If you fork the repository you can make the changes and then send a pull request, no?

**Comment by freddiev4** [comment]
After looking through directories, the above commit that references this issue should be the only problem @JamesJDillon

**Comment by freddiev4** [comment]
Refs #21

**Comment by ghost** [comment]
I've had this problem yesterday with the same folder (Easy - 257), now I am getting the same error for Challenge Easy # 258.
The ":" characters are responsible for this error.
Is there a known way to clone the directory with another name on command line? This type of manipulation is beyond my knowledge, but I would gladly do so to correct the naming scheme of problematic folders.
