### ISSUE TITLE
Re-run script & get latest challenges

### ISSUE THREAD

**Issue by freddiev4** [FreddieV4/DailyProgrammerChallenges#178]
Script was last ran May 7th, and the most recent challenge is 313 it seems.

**Comment by colbygk** [comment]
Hai. I could probably do this.

**Comment by freddiev4** [comment]
@colbygk sure! Give it a go 👍

**Comment by colbygk** [comment]
#181 ready for your perusal

**Comment by freddiev4** [comment]
Fixed by #181 🙂
