### ISSUE TITLE
Adjust Formatting for Directory Names

### ISSUE THREAD

**Issue by freddiev4** [FreddieV4/DailyProgrammerChallenges#20]
From **CONTRIBUTING.md**

> Please use the following name format when creating a challenge directory:
> 
> `Challenge #xxxx [Easy/Intermediate/Hard] Challenge Name`
> 
> Example:
> 
> ```
> Challenge #0251 [Hard] ASCII Nonogram
> Challenge #0254 [Intermediate] Finding Legal Reversi Moves
> Challenge #0253 [Easy] Unconditional Loan Income
> ```

The challenges in `Easy Challenges` have this formatting, but the challenges in `Intermediate Challenges` && `Hard Challenges` do not currently follow this format.

**Comment by nivintw** [comment]
Just submitted a pull request for the Hard Challenges

**Comment by nivintw** [comment]
I used a python script to do the bulk of the work and would be happy to share it. Is there a good way to do that?

It's messy but functional haha

**Comment by freddiev4** [comment]
@tnw346 I'd be glad to add it to this repository, if that's what you want, as I have some shell scripts that do a lot of formatting work, so it could be added as a tool for organizing the repo. How extensible is it? Could I easily change something to run it on `Intermediate` or `Easy` challenges? (even though Easy is already done)

**Comment by nivintw** [comment]
You should be able to duplicate the function and change the references to "hard" to whatever you'd like. As I found while working with the hard challenges, some of them just should be done manually e.g. spelling errors that make automation hard, etc.  but overall it works pretty well.

There should be only a few places in the function that would need to change for Intermediate.

It's only about 40 lines with comments and whitespace
Gist: 
https://gist.github.com/twn346/8e84d11858cbb61503d5

**Comment by nivintw** [comment]
I went ahead and just did the intermediate directory real quick. The script is very easily adjustable. 

I also updated the gist.

**Comment by freddiev4** [comment]
Awesome! @twn346 I'll probably add the script in sometime this weekend to a folder called "Formatting Tools", or something along those lines. 

Fixed by #23 and #22

**Comment by freddiev4** [comment]
@twn346 Added your script

**Comment by nivintw** [comment]
Thanks :)
