### ISSUE TITLE
File naming for open-ended solutions

### ISSUE THREAD

**Issue by causztic** [FreddieV4/DailyProgrammerChallenges#37]
Hello! Just got here from r/ruby and decided to poke around the repository. I've noticed that some challenges e.g. 

https://github.com/FreddieV4/DailyProgrammerChallenges/tree/master/Easy%20Challenges/Challenge%20%230002%20%5BEasy%5D

Are open-ended and the contribution guidelines doesn't cover challenges of this nature; the calculator application can be anything from calculating acceleration to weight of an object, for instance.

We should have a naming convention for these types of challenges too!

**Comment by nodejsjs** [comment]
I second this. Also, many problems are not properly described. By this I mean the I/O is not given properly. Or am I not understanding them?

**Comment by freddiev4** [comment]
@causztic What do you propose that we do for naming conventions of these types of challenges?

@rafid059 They are definitely open ended, but that's based off of the post from r/dailyprogrammer, and that's how it was posted on to the subreddit. I think the challenge should just remain as is, if that's the case.

**Comment by nivintw** [comment]
I agree about preserving the texts as it comes from r/dailyprogrammer, but maybe we can talk to the mods and ask for more consistent formatting with future posts? It would be awesome if they were on board. 

@causztic I'm not sure what you mean, do you mean using something different from "solution.*"? Or did you mean the name of the challenge itself? Is there something about the current naming scheme that doesn't fit for these?

**Comment by freddiev4** [comment]
@twn346 I think that the formatting for posts is _fairly_ consistent now, if you look at the previous 20 challenges or so, probably more. It's just that when the subreddit was first created there wasn't any official formatting, so many of the texts have were written without structure.

**Comment by nivintw** [comment]
Ah ok, that makes sense.

**Comment by causztic** [comment]
@twn346 yeah it's more about the older challenges. The issue was that the challenges are pretty open ended so I felt that the naming of `solution.*` wasn't descriptive enough to serve the purpose.. 

I guess that you could always put comments on the file itself to describe the nature of the solution, but it might be abit too obtuse.

**Comment by freddiev4** [comment]
Adding comments on all of the files that lack any sort of strict guidelines would definitely be quite tedious, though useful.

**Comment by nivintw** [comment]
Could the issue I just posted help this?

**Comment by causztic** [comment]
@twn346 sounds good! the idea of an index of sorts could definitely help. Maybe close this in favor for the other issue you posted?

**Comment by freddiev4** [comment]
Let's migrate this discussion to issue #81 @causztic
