### ISSUE TITLE
Replace 'Trash' in Selftext

### ISSUE THREAD

**Issue by freddiev4** [FreddieV4/DailyProgrammerChallenges#4]
The `challenge_text.md` file of some challenges contain `trash` in it due to some encoding errors while pulling the selftext from the respective r/dailyprogrammer post. 

Challenges Containing Trash:

~~\- Easy Challenges/Challenge # 241 [easy] Unicode Chess/challenge_text.md~~
~~\- Easy Challenges/Challenge #114 [Easy] Word ladder steps/challenge_text.md~~
- Easy Challenges/Challenge #166b [Easy] Planetary Gravity Calculator/challenge_text.md
- Easy Challenges/Challenge #214 [Easy] Calculating the standard deviation/challenge_text.md
- Extra-Bonus Challenges/Challenge #207 [Bonus] Erdos Number Calculator/challenge_text.md
  -Hard Challenges/Challenge # 241 [Hard] Chess Puzzle solver/challenge_text.md
- Hard Challenges/Challenge #121 [Hard] Medal Management/challenge_text.md
- Hard Challenges/Challenge #129 [Hard] Baking Pi/challenge_text.md
- Hard Challenges/Challenge #208 [Hard] The Universal Machine/challenge_text.md
- Hard Challenges/Challenge #248 [Hard] NotClick game/challenge_text.md 
- Hard Challenges/Challenge #50 [difficult]/challenge_text.md
- Intermediate Challenges/Challenge # 241 [intermediate] ascii Bitmap Chess/challenge_text.md
  ~~\- Intermediate Challenges/Challenge #184 [Intermediate] Radioactive Decay/challenge_text.md~~
  ~~\- Intermediate Challenges/Challenge #38 [intermediate]/challenge_text.md~~
  ~~\- Easy Challenges/Challenge #213 [Easy] Cellular Automata - Rule 90/challenge_text.md~~

**Comment by nodejsjs** [comment]
I've updated the text in # 241 [Easy] and # 114 [Easy].

**Comment by kritzware** [comment]
Working on these from the bottom to the top:
I also did #114 [EASY] before seeing the comment from @rafid059
#213 [Easy] - **DONE**
#38 [Intermediate] - **DONE**
#184 [Intermediate] - **DONE**

**Comment by nodejsjs** [comment]
@FreddieV4 You mistakenly crossed off the wrong # 241. It's the top one. The [Easy] one and not the [Hard] one.

**Comment by freddiev4** [comment]
~~@kritzware Are you aware of the name changes to folders in `Easy Challenges`?~~

@rafid059 Thanks just fixed that.

EDIT: @kritzware directory names seem fine.

**Comment by vaz-rodrigo** [comment]
fixed _Extra-Bonus Challenges/Challenge #207 [Bonus] Erdos Number Calculator/challenge_text.md_
fixed _Easy Challenges/Challenge #166b [Easy] Planetary Gravity Calculator/challenge_text.md_
fixed _Easy Challenges/Challenge #214 [Easy] Calculating the standard deviation/challenge_text.md_
fixed _Hard Challenges/Challenge # 241 [Hard] Chess Puzzle solver/challenge_text.md_
fixed _Hard Challenges/Challenge #248 [Hard] NotClick game/challenge_text.md_
fixed _Hard Challenges/Challenge #208 [Hard] The Universal Machine/challenge_text.md_
fixed _Hard Challenges/Challenge #129 [Hard] Baking Pi/challenge_text.md_
fixed _Hard Challenges/Challenge #121 [Hard] Medal Management/challenge_text.md_
fixed _Hard Challenges/Challenge # 50 [difficult]/challenge_text.md_
fixed _Intermediate Challenges/Challenge # 241 [intermediate] ascii Bitmap Chess/challenge_text.md_

**Comment by freddiev4** [comment]
Fixed via PR #74
