### ISSUE TITLE
Challenges that are tightly coupled with input files

### ISSUE THREAD

**Issue by hoenn** [FreddieV4/DailyProgrammerChallenges#69]
The contributing guidelines don't specify what should be done for challenges that are tightly coupled with input files. Example of one is [Intermediate] no.19 which links to text file needed for the program. Should these type of files just be included in the folder for the challenge?

**Comment by freddiev4** [comment]
Personally, I think that the files should just be included in the folder. It could get messy if people started creating new folders for their code **&** their text file. Plus, it's only one extra file per upload.

Otherwise, do you have any suggestions/ideas for the way files/directories are organized?

**Comment by jacobherrington** [comment]
I think all of the solutions should share a text file, like this:

.
├── challenge_text.md
├── _solutions
|   ├── textFileNeededForSolution.txt
|   ├──  solution.xyz
|   ├── solution.rb
|   ├── solution.c
|   └── solution.py

That seems most efficient and would eliminate any unnecessary clutter as well as standardize the file name for whatever input file is needed.

**Comment by freddiev4** [comment]
@jacob-on-github That's essentially the current format, no?

**Comment by nodejsjs** [comment]
@Hoenn @jacob-on-github The text files are already hyper-linked in the challenge_text.md. Adding them separately to the repo is tedious.

**Comment by jacobherrington** [comment]
@rafid059 @FreddieV4 currently they use a hyper link, as rafid said, and while it would be tedious, maybe the should be in the folders as .txt files for the sake of consistency. It's Freddie's call, but I think maybe we should start moving them there.

**Comment by freddiev4** [comment]
I think we can safely say that adding the text, hyperlinked from other sites, will be better, as people will be easily able to continue working through challenges without switching context (i.e. from their text editor to browser).

Let's try compiling a list of challenges that are in fact tightly coupled with their inputs.

**Comment by hoenn** [comment]
Let's add something to the readme or contributing guidelines about the files and close this issue.
