### ISSUE TITLE
Adding Table of Contents like list of the solutions to the challenges directory

### ISSUE THREAD

**Issue by nivintw** [FreddieV4/DailyProgrammerChallenges#81]
Since we'll be having multiple solutions, possibly multiple per-language, I think it'd be nice / beneficial to have a table of contents like log of all of the solutions in the challenge directory, with a short description of the solution. This would encourage people to solve the solution different ways, and could prove a quick overview of the submitted solutions. 

This listing could also include the solution author's name, as a quick view of everyone that contributed to that challenge. 

For example, a solution that utilizes a quick sort could be submitted, and someone or even the same person could also upload a solution that utilizes a randomized quicksort. 

I think it'd also make browsing the repo more user-friendly, as you could relatively easily get a feel for what kind of solutions have already been submitted without having to open every solution file.

Thoughts?

**Comment by freddiev4** [comment]
Would we then come up with descriptions of implementations on our own, for the existing implementations? And then continue to create the descriptions?

Or would contributors be expected to write their own descriptions?

Also, some implementations are based purely on the language and it's capabilities.

**Comment by nivintw** [comment]
My thoughts are to have contributors provide short descriptions of their solutions and add them to the list file when they add their solutions. 

Wouldn't necessarily be a "requirement" but would be nice to have. 
WRT your third point, I think that's even more of a reason to have a short description of the solution. That way, people who wanted to could peruse the repo and find neat things to look at.

**Comment by freddiev4** [comment]
I think it's a good idea, but what will we then do for the _existing_ solutions? There have been a lot merged into this repo.

**Comment by nivintw** [comment]
I don't see it as a mandatory thing. We can ping people to let them know, and they can choose to add a description if they'd like to. 

Going forward, we can just add it to the contributing guide.

**Comment by tlgs** [comment]
I think it's a nice idea as it can introduce people to different algorithms/language functionalities.
It is also easier to compare / visually appealing that in-script comments.
I feel like this would be a lot more helpful when the repo grows bigger; as of now there are plenty of challenges where there are no solutions, let alone multiple ones for the same language.

As a side note, as there been some promoting this repo on the actual subreddit? I feel like there are a lot of people who would happily contribute if they were aware this existed.

**Comment by freddiev4** [comment]
@tlseabra I messaged the moderators and they added it to the `Community Projects` wiki but haven't done any formal announcements.

**Comment by freddiev4** [comment]
Seems like the overall consensus is that this is definitely beneficial and would help people out in their own implementations

**Comment by nivintw** [comment]
I also have an idea to possibly semi-automate this. I'll send a pull request within the next couple of days if I can get my idea flushed out.

**Comment by nivintw** [comment]
Ok, i've done some preliminary work and this seems definitely doable. However, in order to get this right, it'd be extremely helpful if we could agree on a consistent formatting on a few things: 

1) For the header file. If this is consistently formatted, we can parse out some things very easily like author, date, and short description. Here are a couple examples to get the conversation started.

```
# -*- coding: utf-8 -*-
# @Author: Tyler Nivin
# @Date:   Wed Mar 30, 2016 12:23:47 PM
# @Last Modified by:   nivintw
# @Last Modified time: Wed Mar 30, 2016 12:49:48 PM
# @Description: This script intentionally destroys the solutions table
#                and rewrites it completely.
# @Long Description[not required]: A longer description A longer description A longer description A
#                longer description A longer description A longer description A longer description A longer description 
#                A longer description A longer description A longer description A longer description A longer 
#                description A longer description A longer description A longer description 
```

or 

```
/***************************
 * Name: Tyler Nivin
 *
 * Description: A short description 
 * Long Description: See above example.
 * Last Modified: Sun Oct 04, 2015  03:45PM
 **************************/
```

With both, the necessary commenting code would be ignored entirely, and only the comments we wanted to include in the solutions table would be parsed for. Really, the main differences between the two examples are whether or not to include the prepended @ symbol. 
I'm open to any other suggestions as well. These are just my preliminary thoughts.

**Comment by nivintw** [comment]
Additionally, we should support multiple author links, e.g. regular name, github, linkedin etc. 
We could maybe have "Author:" be the "normal" name and the "Github:" etc. be those accounts?
Thoughts?

**Comment by freddiev4** [comment]
I think a simple formatting would work. 

```
/***************************
 * Author: Tyler Nivin
 *
 * Description: A short description 
 * Long Description: See above example.
 * Last Modified: Sun Oct 04, 2015  03:45PM
 **************************/
```

And optional

```
GitHub: github.com/Username
LinkedIn: linkedin.com/in/namename
```

Keeps it short and sweet, but still gives enough info and people can "self promote" with links to their profiles.

**Comment by nivintw** [comment]
Awesome. I'll work on that then. 
Also, our naming convention doesn't play with GitHub's relative linking in markdown at the moment. I've opened an issue [here](https://github.com/github/markup/issues/883) But I don't know for certain that that's even the right place to report the issue. If we get rid of '#' and brackets then we no longer have an issue... 

Are we sure about the naming scheme we want? Now might be a good time to consider other schemes... 

What do you think of:
Challenge 0259 - Clarence the Slow Typist

I would need to test the - symbol to make sure it works correctly, but this might fix the issues i'm having when trying to link to them.

**Comment by nivintw** [comment]
Actually - would conflict with some titles... maybe :?

**Comment by nivintw** [comment]
Well, on that note, including the word "challenge" is a little redundant, but isn't causing issues with anything at the moment.

**Comment by nivintw** [comment]
Ok. I verified that simply removing the '#' and '[' ']' would fix the relative links issue...

**Comment by freddiev4** [comment]
Interesting how the `#` and `[]` symbols mess with relative links. I suppose it's because `#` is used for headers in markdown and `[]` are used to create links in MD as well. I figured that if it's not in markdown, i.e. the name of a directory/file, then it wouldn't recognize that sort of syntax.

**Comment by freddiev4** [comment]
Naming scheme fixed by PR #126

**Comment by freddiev4** [comment]
Fixed in commit 380e8bf

**Comment by nivintw** [comment]
Isn't quite finished yet actually, I haven't finished the TOS. But this can stay closed if you want, I have a plan and will submit a pull request when I finish.

**Comment by FreddieV4** [comment]
@twn346 Will reopen :)
